root: ./docs/help-center/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  # Old paths redirect to new help center structure
  quick-start: get-started/quick-start.md
  faq: reference/faq.md
  shortcuts: editor/keyboard-shortcuts.md
