name: "Feature / spec"
description: "Larger feature or change that needs some design before coding."
title: "[Feature] "
labels:
  - feature
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: "One-line description of the feature."
      placeholder: "Show per-job cost in tokens and EUR"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "Why is this feature needed? What pain does it solve?"
      placeholder: "Users cannot see how much each job costs them in LLM usage, so pricing and budgeting are hard."

  - type: textarea
    id: user_story
    attributes:
      label: User story
      description: "Use the format: As a…, I want…, so that…"
      placeholder: "As a Supervertaler user, I want to see a cost breakdown per job so that I can understand and control my LLM spending."

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: "Bullet list of what must be true for this to be done. Checkboxes are fine."
      placeholder: |
        - [ ] Track token usage per job, per model.
        - [ ] Convert tokens to approximate EUR using config prices.
        - [ ] Show a simple per-job report vi
